var translationsFR = {
    BRAND: 'Outils Symbaroum',
    SEARCH: 'Recherche',
    LIENS: 'Liens externes',
    HELP: 'Aide',
    REGLES: 'Règles',
    TRUE: 'Oui',
    FALSE: 'Non',
    TYPE_TOUS: 'Type (tous)',
    TYPE_TALENT: 'talent',
    TYPE_POUVOIR_MYSTIQUE: 'pouvoir mystique',
    TYPE_QUALITE: 'qualite',
    TYPE_TRAIT_MONSTRUEUX: 'trait monstrueux',
    TYPE_TRAIT: 'trait',
    TYPE_ATOUT: 'atout',
    TYPE_FARDEAU: 'fardeau',
    TYPE_ELIXIR: 'elixir',
    TYPE_RITUEL: 'rituel',
    TYPE_ARME: 'arme',
    TYPE_ARMURE: 'armure',
    BOOK: 'Livre',
    BOOK_TOUS: 'Livre (tous)',
    BOOK_LDB: 'livre de base',
    BOOK_GDJ: 'guide du joueur',
    BOOK_CDX: 'codex des monstres',
    TRAD_TOUS: 'Arch./Trad. (toutes)',
    TRAD_AUCUNE: 'aucune',
    TRAD_GUERRIER: 'guerrier',
    TRAD_MYSTIQUE: 'mystique',
    TRAD_ROUBLARD: 'roublard',
    TRAD_CHASSEUR: 'chasseur',
    TRAD_MAGIE: 'magie',
    TRAD_THEURGIE: 'théurgie',
    TRAD_SORCELLERIE: 'sorcellerie',
    TRAD_CONJURATION: 'conjuration',
    TRAD_TROLLS: 'chant des trolls',
    TRAD_SYMBOLISME: 'symbolisme',
    TRAD_BATON: 'mages au bâton',
    NAME: 'Nom',
    AGI: 'AGI',
    FOR: 'FOR',
    PRE: 'PRE',
    VOL: 'VOL',
    VIG: 'VIG',
    DIS: 'DIS',
    AST: 'AST',
    PER: 'PER',
    INIT: 'INIT',
    INITIATIVE: 'Initiative',
    CATEG: 'Catégorie',
    DEF: 'DEF',
    END: 'END',
    SD: 'SD',
    SC: 'SC',
    CP: 'CP',
    DEG: 'DEG',
    ARM: 'ARM',
    DEFENSE: 'Défense',
    ARMURE: 'Armure',
    ENDURANCE: 'Endurance',
    RES_DOUL: 'Résistance à la douleur',
    SEUIL_CORR: 'Seuil de corruption',
    PERM_CORR: 'Corruption permanente',
    ARMES: 'Armes',
    TALENTS: 'Talents',
    TRAITS: 'Traits',
    NOTES: 'Notes',
    TACTICS: 'Tactiques',
    SHADOW: 'Ombre',
    EQUIPMENT: 'Equipement',
    EXPORT: 'Export JSON',
    SAVE: 'Sauvegarder',
    COPIED: ' copié',
    IMPORT_JSON: 'Import JSON',
    B64: 'Générer un lien',
    DISP_DESC: 'Afficher descriptions',
    RECH_DESC: 'Recherche aussi dans description',
    PINS: 'Epinglés seulement',
    PINS_TITLE: "N'afficher que les talents épinglés, que ce soit au niveau du nom du talent (dans ce cas, tous les niveaux sont visibles) ou d'un ou des niveaux (dans ce cas, seuls les niveaux épinglés sont visibles).",
    SEARCH_TITLE: "Champ de recherche. Les mots clés doivent être séparés par une virgule. Terminer par une virgule pour tout afficher à nouveau. Exemple : 'berserk,vif,'.",
    EXPORT_TITLE: "Format JSON",
    DOWNLOAD: "Télécharger",
    FOUNDRY_EXPORT_TITLE: "Macro FoundryVTT",
    FOUNDRY_EXPORT: "Copier le JSON dans le presse-papier",
    B64_TITLE: "Générer un lien encodé.",
    PINS_TITLE_ALL: 'Epingler entièrement.',
    PINS_TITLE_NOV: 'Epingler le niveau novice.',
    PINS_TITLE_ADP: 'Epingler le niveau adepte.',
    PINS_TITLE_MAI: 'Epingler le niveau maitre.',
    B84_PAN_TITLE: "Favoris",
    B84_PAN_LINK: "Lien",
    PAN_CLOSE: "Fermer",
    ATTR_TOUS: "Test (tous)",
    ATTR_AST: "Astuce",
    ATTR_DIS: "Discrétion",
    ATTR_AGI: "Agilité",
    ATTR_PER: "Persuasion",
    ATTR_FOR: "Force",
    ATTR_VIG: "Vigilance",
    ATTR_VOL: "Volonté",
    ATTR_PRE: "Précision",
    ATTR_PERVOL: "Persuasion <- Volonté",
    ATTR_ASTFOR: "Astuce <- Force",
    ATTR_ASTAST: "Astuce <- Astuce",
    ATTR_DISVIG: "Discrétion <- Vigilance",
    ATTR_FORFOR: "Force <- Force",
    ATTR_PREFOR: "Précision <- Force",
    ATTR_PREAGI: "Précision <- Agilité",
    ATTR_ASTAGI: "Astuce <- Agilité",
    ATTR_AGIFOR: "Agilité <- Force",
    ATTR_PREVOL: "Précision <- Volonté",
    ATTR_FORAGI: "Force <- Agilité",
    DAV_CLAIR: "Clair",
    DAV_SAUVAGE: "Sauvage",
    DAV_SOMBRE: "Sombre",
    DAV_SURVIE: "Survie",
    NOVICE: "Novice",
    ADEPTE: "Adepte",
    MAITRE: "Maître",
    DAV_JOURNEE: "Passer une journée en Davokar",
    DAV_TRESORS: "Trésors trouvés",
    DAV_PROV: "Provisions",
    DAV_NBPJ: "Nb. PNJ",
    DAV_SURPLACE: "Rester sur place",
    DAV_INFO: "Information orale",
    DAV_INFO_ECRITE: "Source écrite",
    DAV_INFO_ECRITE_SUP5: "Réussite jet > 5",
    DAV_ORIENTATION: "Orientation",
    DAV_RUINE: "Ruine",
    DAV_TRESOR: "Trésor",
    DAV_RENCONTRE: "Rencontre",
    DAV_ENNEMI: "Ennemis",
    DAV_TERRAIN: "Terrain",
    DAV_NONE: "Rien.",
    DAV_DEBRIS: "Débris",
    DAV_CURIOSITE: "Curiosité",
    DAV_MYSTIQUE: "Trésor mystique",
    DAV_ARTEFACT: "Artefact",
    DAV_ALERTE_VIG: "Saisir la Vigilance du chercheur de trésor !",
    DAV_REPERE: " Vous n'avez pas été repéré.",
    DAV_TRES_RESTANT: "Restant",
    AJOUT_ACTEUR: "Ajouter un acteur",
    SORT_INIT: "Trier",
    HIDE_ABILITIES: "Cacher la description des talents",
    NEW_TAB: "Ouvrir dans un nouvel onglet",
    MANAGE_INTEGRATED: "Gérer les talents intégrés",
    INTEGRATED: "Intégré",
    SPENT_POINTS: "Pts. Dépensés : ",
    STD_ARRAY: "Répartition classique : "
};

var translationsES = {
    BRAND: 'Herramientas de Symbaroum',
    SEARCH: 'Buscar',
    LIENS: 'Enlaces externos',
    HELP: 'Ayuda',
    REGLES: 'Reglas',
    TRUE: 'Sí',
    FALSE: 'No',
    TYPE_TOUS: 'Tipo (todos)',
    TYPE_TALENT: 'habilidad',
    TYPE_POUVOIR_MYSTIQUE: 'poder místico',
    TYPE_QUALITE: 'cualidad',
    TYPE_TRAIT_MONSTRUEUX: 'rasgo de monstruo',
    TYPE_TRAIT: 'rasgo',
    TYPE_ATOUT: 'don',
    TYPE_FARDEAU: 'carga',
    TYPE_ELIXIR: 'elixires',
    TYPE_RITUEL: 'ritual',
    TYPE_ARME: 'arma',
    TYPE_ARMURE: 'armadura',
    BOOK: 'Libro',
    BOOK_TOUS: 'Libro (todos)',
    BOOK_LDB: 'libro básico',
    BOOK_GDJ: 'guía del jugador avanzado',
    BOOK_CDX: 'códice monstruo',
    TRAD_TOUS: 'Arq./Trad. (todas)',
    TRAD_AUCUNE: 'ninguno',
    TRAD_GUERRIER: 'guerrero',
    TRAD_MYSTIQUE: 'místico',
    TRAD_ROUBLARD: 'maleante',
    TRAD_CHASSEUR: 'cazador',
    TRAD_MAGIE: 'magia',
    TRAD_THEURGIE: 'teúrgia',
    TRAD_SORCELLERIE: 'brujería',
    TRAD_CONJURATION: 'hechicería',
    TRAD_TROLLS: 'cantar troll',
    TRAD_SYMBOLISME: 'simbolismo',
    TRAD_BATON: 'magia del báculo',
    NAME: 'Nombre',
    AGI: 'AGI',
    FOR: 'FUE',
    PRE: 'DIE',
    VOL: 'TEN',
    VIG: 'ATE',
    DIS: 'DIS',
    AST: 'INT',
    PER: 'PER',
    INIT: 'INIC',
    INITIATIVE: 'Iniciativa',
    CATEG: 'Categoría',
    DEF: 'DEF',
    END: 'RES',
    SD: 'UD', //pain treshold
    SC: 'UC', // corruption treshold
    CP: 'CP', // 
    DEG: 'DAÑ', // damages
    ARM: 'ARM', // armor
    DEFENSE: 'Defensa',
    ARMURE: 'Armadura',
    ENDURANCE: 'Resistencia',
    RES_DOUL: 'Umbral de Dolor',
    SEUIL_CORR: 'Umbral de Corrupción',
    PERM_CORR: 'Corrupción Permanente',
    ARMES: 'Armas',
    TALENTS: 'Habilidades',
    TRAITS: 'Rasgos',
    NOTES: 'Notas',
    TACTICS: 'Tácticas',
    SHADOW: 'Sombra',
    EQUIPMENT: 'Equipo',
    EXPORT: 'Exportar JSON',
    SAVE: 'Guardar',
    COPIED: ' copiar',
    IMPORT_JSON: 'Importar JSON',
    B64: 'Generar enlace',
    DISP_DESC: 'Mostrar descripciones',
    RECH_DESC: 'Buscar en descripción',
    PINS: 'Solo fijados',
    PINS_TITLE: "Mostrar solo elementos fijados, sean fijados de manera global (en ese caso todos los niveles son visibles) o solo un nivel específico (en ese caso solo los niveles fijados son visibles).",
    SEARCH_TITLE: "Campo de búsqueda. Las palabras clave deben separarse por una coma. Terminar con una coma mostrará todos. Ejemplo :  'berserker,acro,'.",
    EXPORT_TITLE: "Formato JSON",
    DOWNLOAD: "Descargar",
    FOUNDRY_EXPORT_TITLE: "Macro FoundryVTT",
    FOUNDRY_EXPORT: "Copia el JSON al portapapeles",
    B64_TITLE: "Generar un enlace (codificado).",
    PINS_TITLE_ALL: 'Fijar la carta entera.',
    PINS_TITLE_NOV: 'Fijar nivel Principiante.',
    PINS_TITLE_ADP: 'Fijar nivel Adepto.',
    PINS_TITLE_MAI: 'Fijar nivel Maestro.',
    B84_PAN_TITLE: "Marcadores",
    B84_PAN_LINK: "Enlace",
    PAN_CLOSE: "Cerrar",
    ATTR_TOUS: "Prueba (todo)",
    ATTR_AST: "Inteligente",
    ATTR_DIS: "Discreto",
    ATTR_AGI: "Ágil",
    ATTR_PER: "Persuasivo",
    ATTR_FOR: "Fuerte",
    ATTR_VIG: "Atento",
    ATTR_VOL: "Tenaz",
    ATTR_PRE: "Diestro",
    ATTR_PERVOL: "Persuasivo <- Tenaz",
    ATTR_ASTFOR: "Inteligente <- Fuerte",
    ATTR_ASTAST: "Inteligente <- Inteligente",
    ATTR_DISVIG: "Discreto <- Atento",
    ATTR_FORFOR: "Fuerte <- Fuerte",
    ATTR_PREFOR: "Diestro <- Fuerte",
    ATTR_PREAGI: "Diestro <- Ágil",
    ATTR_ASTAGI: "Inteligente <- Ágil",
    ATTR_AGIFOR: "Ágil <- Fuerte",
    ATTR_PREVOL: "Diestro <- Tenaz",
    ATTR_FORAGI: "Fuerte <- Ágil",
    AJOUT_ACTEUR: "Agregar actor",
    SORT_INIT: "Ordenar",
    HIDE_ABILITIES: "Esconder descripción de habilidades",
    NEW_TAB: "Abre en una nueva pestaña",
    MANAGE_INTEGRATED: "Gestionar habilidades integradas",
    INTEGRATED: "Integrada",
    SPENT_POINTS: "Gastó puntos: ",
    STD_ARRAY: "Reparto estándar: "
};

var translationsEN = {
    BRAND: 'Symbaroum Tools',
    SEARCH: 'Search',
    LIENS: 'External Links',
    HELP: 'Help',
    REGLES: 'Rules',
    TRUE: 'Yes',
    FALSE: 'No',
    TYPE_TOUS: 'Type (all)',
    TYPE_TALENT: 'ability',
    TYPE_POUVOIR_MYSTIQUE: 'mystical power',
    TYPE_QUALITE: 'quality',
    TYPE_TRAIT_MONSTRUEUX: 'monstruous trait',
    TYPE_TRAIT: 'trait',
    TYPE_ATOUT: 'boon',
    TYPE_FARDEAU: 'burden',
    TYPE_ELIXIR: 'potion',
    TYPE_RITUEL: 'ritual',
    TYPE_ARME: 'weapon',
    TYPE_ARMURE: 'armor',
    BOOK: 'Book',
    BOOK_TOUS: 'Book (all)',
    BOOK_LDB: 'core rulebook',
    BOOK_GDJ: 'advanced player guide',
    BOOK_CDX: 'monster codex',
    TRAD_TOUS: 'Arch./Trad. (all)',
    TRAD_AUCUNE: 'none',
    TRAD_GUERRIER: 'warrior',
    TRAD_MYSTIQUE: 'mystic',
    TRAD_ROUBLARD: 'rogue',
    TRAD_CHASSEUR: 'hunter',
    TRAD_MAGIE: 'wizardry',
    TRAD_THEURGIE: 'theurgy',
    TRAD_SORCELLERIE: 'witchcraft',
    TRAD_CONJURATION: 'sorcery',
    TRAD_TROLLS: 'troll singing',
    TRAD_SYMBOLISME: 'symbolism',
    TRAD_BATON: 'staff magic',
    NAME: 'Name',
    AGI: 'QUI',
    FOR: 'STR',
    PRE: 'ACC',
    VOL: 'RES',
    VIG: 'VIG',
    DIS: 'DIS',
    AST: 'CUN',
    PER: 'PER',
    INIT: 'INIT',
    INITIATIVE: 'Initiative',
    CATEG: 'Category',
    DEF: 'DEF',
    END: 'TOU',
    SD: 'PT',
    SC: 'CT',
    CP: 'PC',
    DEG: 'DAM',
    ARM: 'ARM',
    DEFENSE: 'Defense',
    ARMURE: 'Armor',
    ENDURANCE: 'Toughness',
    RES_DOUL: 'Pain Threshold',
    SEUIL_CORR: 'Corruption Threshold',
    PERM_CORR: 'Permanent Corruption',
    ARMES: 'Weapons',
    TALENTS: 'Abilities',
    TRAITS: 'Traits',
    NOTES: 'Notes',
    TACTICS: 'Tactics',
    SHADOW: 'Shadow',
    EQUIPMENT: 'Equipment',
    EXPORT: 'JSON Export',
    SAVE: 'Save',
    COPIED: ' copied',
    IMPORT_JSON: 'JSON Import',
    B64: 'Generate link',
    DISP_DESC: 'Display descriptions',
    RECH_DESC: 'Search in description',
    PINS: 'Pinned only',
    PINS_TITLE: "Only display pinned things, either if they have been pinned globaly (in this case all levels are visibles) or by a specific leve (in this case, only pinned levels are visibles).",
    SEARCH_TITLE: "Search field. Keywords must be coma separated. End with a comma will display all. Example : 'berserk,acro,'.",
    EXPORT_TITLE: "JSON format",
    DOWNLOAD: "Download",
    FOUNDRY_EXPORT_TITLE: "FoundryVTT Macro",
    FOUNDRY_EXPORT: "Copy JSON to clipboard",
    B64_TITLE: "Generate a link (encoded).",
    PINS_TITLE_ALL: 'Pin the whole card.',
    PINS_TITLE_NOV: 'Pin novice level.',
    PINS_TITLE_ADP: 'Pin adept level.',
    PINS_TITLE_MAI: 'Pin master level.',
    B84_PAN_TITLE: "Bookmark",
    B84_PAN_LINK: "Link",
    PAN_CLOSE: "Close",
    ATTR_TOUS: "Test (all)",
    ATTR_AST: "Cunning",
    ATTR_DIS: "Discretion",
    ATTR_AGI: "Quick",
    ATTR_PER: "Persuasion",
    ATTR_FOR: "Strength",
    ATTR_VIG: "Vigilance",
    ATTR_VOL: "Resolute",
    ATTR_PRE: "Accurate",
    ATTR_PERVOL: "Persuasion <- Resolute",
    ATTR_ASTFOR: "Cunning <- Strength",
    ATTR_ASTAST: "Cunning <- Cunning",
    ATTR_DISVIG: "Discretion <- Vigilance",
    ATTR_FORFOR: "Strength <- Strength",
    ATTR_PREFOR: "Accurate <- Strength",
    ATTR_PREAGI: "Accurate <- Quick",
    ATTR_ASTAGI: "Cunning <- Quick",
    ATTR_AGIFOR: "Quick <- Strength",
    ATTR_PREVOL: "Accurate <- Resolute",
    ATTR_FORAGI: "Strength <- Quick",
    DAV_CLAIR: "Bright",
    DAV_SAUVAGE: "Wild",
    DAV_SOMBRE: "Dark",
    DAV_SURVIE: "Bushcraft",
    NOVICE: "Novice",
    ADEPTE: "Adept",
    MAITRE: "Master",
    DAV_JOURNEE: "Spend a day in Davokar",
    DAV_TRESORS: "Found Treasures",
    DAV_PROV: "Supplies",
    DAV_NBPJ: "NPC nb.",
    DAV_SURPLACE: "Stay on Site",
    DAV_INFO: "Information from People",
    DAV_INFO_ECRITE: "Written Sources",
    DAV_INFO_ECRITE_SUP5: "Roll Success > 5",
    DAV_ORIENTATION: "Orientation",
    DAV_RUINE: "Ruin",
    DAV_TRESOR: "Treasure",
    DAV_RENCONTRE: "Encounter",
    DAV_ENNEMI: "Enemies",
    DAV_TERRAIN: "Terrain",
    DAV_NONE: "None.",
    DAV_DEBRIS: "Debris",
    DAV_CURIOSITE: "Curiosity",
    DAV_MYSTIQUE: "Mystical treasure",
    DAV_ARTEFACT: "Artifact",
    DAV_ALERTE_VIG: "Fill treasure hunter Vigilance !",
    DAV_REPERE: " You have not been spotted.",
    DAV_TRES_RESTANT: "Remaining",
    AJOUT_ACTEUR: "Add actor",
    SORT_INIT: "Sort",
    HIDE_ABILITIES: "Hide abilities descriptions",
    NEW_TAB: "Open in a New Tab",
    MANAGE_INTEGRATED: "Manage integrated abilities",
    INTEGRATED: "Integrated",
    SPENT_POINTS: "Spent Points: ",
    STD_ARRAY: "Standard Array: "
};