var translationsES = {
    BRAND: 'Herramientas de Symbaroum',
    SEARCH: 'Buscar',
    LIENS: 'Enlaces externos',
    HELP: 'Ayuda',
    REGLES: 'Reglas',
    TRUE: 'Sí',
    FALSE: 'No',
    TYPE_TOUS: 'Tipo (todos)',
    TYPE_TALENT: 'habilidad',
    TYPE_POUVOIR_MYSTIQUE: 'poder místico',
    TYPE_QUALITE: 'cualidad',
    TYPE_TRAIT_MONSTRUEUX: 'rasgo de monstruo',
    TYPE_TRAIT: 'rasgo',
    TYPE_ATOUT: 'don',
    TYPE_FARDEAU: 'carga',
    TYPE_ELIXIR: 'elixires',
    TYPE_RITUEL: 'ritual',
    TYPE_ARME: 'arma',
    TYPE_ARMURE: 'armadura',
    BOOK: 'Libro',
    BOOK_TOUS: 'Libro (todos)',
    BOOK_LDB: 'libro básico',
    BOOK_GDJ: 'guía del jugador avanzado',
    BOOK_CDX: 'códice monstruo',
    BOOK_ADV: 'aventuras',
    TRAD_TOUS: 'Arq./Trad. (todas)',
    TRAD_AUCUNE: 'ninguno',
    TRAD_GUERRIER: 'guerrero',
    TRAD_MYSTIQUE: 'místico',
    TRAD_ROUBLARD: 'maleante',
    TRAD_CHASSEUR: 'cazador',
    TRAD_MAGIE: 'magia',
    TRAD_THEURGIE: 'teúrgia',
    TRAD_SORCELLERIE: 'brujería',
    TRAD_CONJURATION: 'hechicería',
    TRAD_TROLLS: 'cantar troll',
    TRAD_SYMBOLISME: 'simbolismo',
    TRAD_BATON: 'magia del báculo',
    TRAD_BLESSING: 'bendición',
    NAME: 'Nombre',
    AGI: 'AGI',
    FOR: 'FUE',
    PRE: 'DIE',
    VOL: 'TEN',
    VIG: 'ATE',
    DIS: 'DIS',
    AST: 'INT',
    PER: 'PER',
    INIT: 'INIC',
    INITIATIVE: 'Iniciativa',
    CATEG: 'Categoría',
    DEF: 'DEF',
    END: 'RES',
    SD: 'UD', //pain treshold
    SC: 'UC', // corruption treshold
    CP: 'CP', // 
    DEG: 'DAÑ', // damages
    ARM: 'ARM', // armor
    DEFENSE: 'Defensa',
    ARMURE: 'Armadura',
    ENDURANCE: 'Resistencia',
    RES_DOUL: 'Umbral de Dolor',
    SEUIL_CORR: 'Umbral de Corrupción',
    PERM_CORR: 'Corrupción Permanente',
    ARMES: 'Armas',
    TALENTS: 'Habilidades',
    TRAITS: 'Rasgos',
    NOTES: 'Notas',
    TACTICS: 'Tácticas',
    SHADOW: 'Sombra',
    EQUIPMENT: 'Equipo',
    EXPORT: 'Exportar',
    SAVE: 'Guardar',
    COPIED: ' copiar',
    IMPORT_JSON: 'Importar',
    B64: 'Generar enlace',
    DISP_DESC: 'Mostrar descripciones',
    RECH_DESC: 'Buscar en descripción',
    PINS: 'Solo fijados',
    PINS_TITLE: "Mostrar solo elementos fijados, sean fijados de manera global (en ese caso todos los niveles son visibles) o solo un nivel específico (en ese caso solo los niveles fijados son visibles).",
    SEARCH_TITLE: "Campo de búsqueda. Las palabras clave deben separarse por una coma. Terminar con una coma mostrará todos. Ejemplo :  'berserker,acro,'.",
    EXPORT_TITLE: "Formato JSON",
    DOWNLOAD: "Descargar",
    FOUNDRY_EXPORT_TITLE: "Macro FoundryVTT",
    FOUNDRY_EXPORT: "Copia el JSON al portapapeles",
    B64_TITLE: "Generar un enlace (codificado).",
    PINS_TITLE_ALL: 'Fijar la carta entera.',
    PINS_TITLE_NOV: 'Fijar nivel Principiante.',
    PINS_TITLE_ADP: 'Fijar nivel Adepto.',
    PINS_TITLE_MAI: 'Fijar nivel Maestro.',
    B84_PAN_TITLE: "Marcadores",
    B84_PAN_LINK: "Enlace",
    PAN_CLOSE: "Cerrar",
    ATTR_TOUS: "Prueba (todo)",
    ATTR_AST: "Inteligente",
    ATTR_DIS: "Discreto",
    ATTR_AGI: "Ágil",
    ATTR_PER: "Persuasivo",
    ATTR_FOR: "Fuerte",
    ATTR_VIG: "Atento",
    ATTR_VOL: "Tenaz",
    ATTR_PRE: "Diestro",
    ATTR_PERVOL: "Persuasivo <- Tenaz",
    ATTR_ASTFOR: "Inteligente <- Fuerte",
    ATTR_ASTAST: "Inteligente <- Inteligente",
    ATTR_DISVIG: "Discreto <- Atento",
    ATTR_FORFOR: "Fuerte <- Fuerte",
    ATTR_PREFOR: "Diestro <- Fuerte",
    ATTR_PREAGI: "Diestro <- Ágil",
    ATTR_ASTAGI: "Inteligente <- Ágil",
    ATTR_AGIFOR: "Ágil <- Fuerte",
    ATTR_PREVOL: "Diestro <- Tenaz",
    ATTR_FORAGI: "Fuerte <- Ágil",
    AJOUT_ACTEUR: "Agregar actor",
    SORT_INIT: "Ordenar",
    HIDE_ABILITIES: "Esconder descripción de habilidades",
    NEW_TAB: "Abre en una nueva pestaña",
    MANAGE_INTEGRATED: "Gestionar habilidades integradas",
    INTEGRATED: "Integrada",
    SPENT_POINTS: "Gastó puntos: ",
    STD_ARRAY: "Reparto estándar: ",
    OPEN: "Abrir",
    MY_PC_NPC: "Mi PJ/PNJ/Monstruos",
    SESSION_MSG: "Advertencia, este sitio Web no administra sesiones, no actualice la página o deberá volver a autenticarse.",
    LOG_IN: "Conexión",
    SIGN_UP: "Registro",
    PWD: "Contraseña",
    EMAIL: "Correo electrónico",
    LOGOUT: "cerrar sesión",

    // SymbatooTools API errors
    ERR_LOG_1: "Correo electrónico desconocida.",
    ERR_LOG_2: "Contraseña incorrecta.",
    ERR_LOG_3: "Cuenta pendiente de validación.",
    ERR_REG_1: "Falta correo electrónico o la contraseña.",
    ERR_REG_2: "Formato de correo electrónico no válido.",
    ERR_REG_3: "Correo electrónico ya registrado.",
    ERR_REG_4: "No se envió el correo electrónico de validación, comuníquese con el administrador.",
    ERR_RES_1: "No se envió el correo electrónico de restablecimiento de contraseña, comuníquese con el administrador."
};