
var translationsEN = {
    BRAND: 'Symbaroum Tools',
    SEARCH: 'Search',
    LIENS: 'External links',
    HELP: 'Help',
    REGLES: 'Rules',
    TRUE: 'Yes',
    FALSE: 'No',
    TYPE_TOUS: 'Type (all)',
    TYPE_TALENT: 'ability',
    TYPE_POUVOIR_MYSTIQUE: 'mystical power',
    TYPE_QUALITE: 'quality',
    TYPE_TRAIT_MONSTRUEUX: 'monstruous trait',
    TYPE_TRAIT: 'trait',
    TYPE_ATOUT: 'boon',
    TYPE_FARDEAU: 'burden',
    TYPE_ELIXIR: 'potion',
    TYPE_RITUEL: 'ritual',
    TYPE_ARME: 'weapon',
    TYPE_ARMURE: 'armor',
    BOOK: 'Book',
    BOOK_TOUS: 'Book (all)',
    BOOK_LDB: 'core rulebook',
    BOOK_GDJ: 'advanced player guide',
    BOOK_CDX: 'monster codex',
    BOOK_ADV: 'adventures',
    TRAD_TOUS: 'Arch./Trad. (all)',
    TRAD_AUCUNE: 'none',
    TRAD_GUERRIER: 'warrior',
    TRAD_MYSTIQUE: 'mystic',
    TRAD_ROUBLARD: 'rogue',
    TRAD_CHASSEUR: 'hunter',
    TRAD_MAGIE: 'wizardry',
    TRAD_THEURGIE: 'theurgy',
    TRAD_SORCELLERIE: 'witchcraft',
    TRAD_CONJURATION: 'sorcery',
    TRAD_TROLLS: 'troll singing',
    TRAD_SYMBOLISME: 'symbolism',
    TRAD_BATON: 'staff magic',
    TRAD_BLESSING: 'blessing',
    NAME: 'Name',
    AGI: 'QUI',
    FOR: 'STR',
    PRE: 'ACC',
    VOL: 'RES',
    VIG: 'VIG',
    DIS: 'DIS',
    AST: 'CUN',
    PER: 'PER',
    INIT: 'INIT',
    INITIATIVE: 'Initiative',
    CATEG: 'Category',
    DEF: 'DEF',
    END: 'TOU',
    SD: 'PT',
    SC: 'CT',
    CP: 'PC',
    DEG: 'DAM',
    ARM: 'ARM',
    DEFENSE: 'Defense',
    ARMURE: 'Armor',
    ENDURANCE: 'Toughness',
    RES_DOUL: 'Pain threshold',
    SEUIL_CORR: 'Corruption threshold',
    PERM_CORR: 'Permanent corruption',
    ARMES: 'Weapons',
    TALENTS: 'Abilities',
    TRAITS: 'Traits',
    NOTES: 'Notes',
    TACTICS: 'Tactics',
    SHADOW: 'Shadow',
    EQUIPMENT: 'Equipment',
    EXPORT: 'Export',
    SAVE: 'Save',
    COPIED: ' copied',
    IMPORT_JSON: 'Import',
    B64: 'Generate link',
    DISP_DESC: 'Display descriptions',
    RECH_DESC: 'Search in description',
    PINS: 'Pinned only',
    PINS_TITLE: "Only display pinned things, either if they have been pinned globaly (in this case all levels are visibles) or by a specific leve (in this case, only pinned levels are visibles).",
    SEARCH_TITLE: "Search field. Keywords must be coma separated. End with a comma will display all. Example : 'berserk,acro,'.",
    EXPORT_TITLE: "JSON format",
    DOWNLOAD: "Download",
    FOUNDRY_EXPORT_TITLE: "FoundryVTT macro",
    FOUNDRY_EXPORT: "Copy JSON to clipboard",
    B64_TITLE: "Generate a link (encoded).",
    PINS_TITLE_ALL: 'Pin the whole card.',
    PINS_TITLE_NOV: 'Pin novice level.',
    PINS_TITLE_ADP: 'Pin adept level.',
    PINS_TITLE_MAI: 'Pin master level.',
    B84_PAN_TITLE: "Bookmark",
    B84_PAN_LINK: "Link",
    PAN_CLOSE: "Close",
    ATTR_TOUS: "Test (all)",
    ATTR_AST: "Cunning",
    ATTR_DIS: "Discretion",
    ATTR_AGI: "Quick",
    ATTR_PER: "Persuasion",
    ATTR_FOR: "Strength",
    ATTR_VIG: "Vigilance",
    ATTR_VOL: "Resolute",
    ATTR_PRE: "Accurate",
    ATTR_PERVOL: "Persuasion <- Resolute",
    ATTR_ASTFOR: "Cunning <- Strength",
    ATTR_ASTAST: "Cunning <- Cunning",
    ATTR_DISVIG: "Discretion <- Vigilance",
    ATTR_FORFOR: "Strength <- Strength",
    ATTR_PREFOR: "Accurate <- Strength",
    ATTR_PREAGI: "Accurate <- Quick",
    ATTR_ASTAGI: "Cunning <- Quick",
    ATTR_AGIFOR: "Quick <- Strength",
    ATTR_PREVOL: "Accurate <- Resolute",
    ATTR_FORAGI: "Strength <- Quick",
    DAV_CLAIR: "Bright",
    DAV_SAUVAGE: "Wild",
    DAV_SOMBRE: "Dark",
    DAV_SURVIE: "Bushcraft",
    NOVICE: "Novice",
    ADEPTE: "Adept",
    MAITRE: "Master",
    DAV_JOURNEE: "Spend a day in Davokar",
    DAV_TRESORS: "Found treasures",
    DAV_PROV: "Supplies",
    DAV_NBPJ: "NPC nb.",
    DAV_SURPLACE: "Stay on Site",
    DAV_INFO: "Information from people",
    DAV_INFO_ECRITE: "Written sources",
    DAV_INFO_ECRITE_SUP5: "Roll success > 5",
    DAV_ORIENTATION: "Orientation",
    DAV_RUINE: "Ruin",
    DAV_TRESOR: "Treasure",
    DAV_RENCONTRE: "Encounter",
    DAV_ENNEMI: "Enemies",
    DAV_TERRAIN: "Terrain",
    DAV_NONE: "None.",
    DAV_DEBRIS: "Debris",
    DAV_CURIOSITE: "Curiosity",
    DAV_MYSTIQUE: "Mystical treasure",
    DAV_ARTEFACT: "Artifact",
    DAV_ALERTE_VIG: "Fill treasure hunter Vigilance !",
    DAV_REPERE: " You have not been spotted.",
    DAV_TRES_RESTANT: "Remaining",
    AJOUT_ACTEUR: "Add actor",
    SORT_INIT: "Sort",
    HIDE_ABILITIES: "Hide abilities descriptions",
    NEW_TAB: "Open in a new tab",
    MANAGE_INTEGRATED: "Manage integrated abilities",
    INTEGRATED: "Integrated",
    SPENT_POINTS: "Spent points: ",
    STD_ARRAY: "Standard array: ",
    OPEN: "Open",
    MY_PC_NPC: "My PC/NPC/Monsters",

    // User managerment
    SESSION_MSG: "Be aware that this Web site does not manage sessions, so do not refresh or you will need to reauthenticate.",
    LOG_IN: "Log in",
    SIGN_UP: "Sign up",
    PWD: "Password",
    PWD_CONFIRM: "Password confirmation",
    EMAIL: "Email address",
    LOGOUT: "Logout",
    MSG_EMAIl_FORMAT: "Must be a valid email address format",
    MSG_PWD_STR: "Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters",
    CHANGE_PWD: "Change password",
    MSG_PWD_DIFF: "Values are different",
    TOOKEN_VAL: "Validate",
    LOST_PWD: "I forgot my password",
    MSG_LOST_PWD: "Hey, I lost my password, please help me !",
    

    // SymbatooTools API errors
    ERR_LOG_1: "Unknown email address.",
    ERR_LOG_2: "Incorrect password.",
    ERR_LOG_3: "Account pending validation.",
    ERR_REG_1: "Missing email address or password.",
    ERR_REG_2: "Wrong email address format.",
    ERR_REG_3: "Email address already registered.",
    ERR_REG_4: "Validation email not sent, please contact the administrator.",
    ERR_RES_1: "Password reset email not sent, please contact the administrator.",
    ERR_API_1: "The request was sent but is not valid, please contact the administrator.",

    // SymbaTools reset pwd messages
    MSG_RES_EMAIL_SENT: 'An email has been sent to you with the token to enter.',
    MSG_RES_TOKEN_OK: 'The token has been validated, please enter you new password.',
    MSG_RES_PWD_CHANGED: 'Your password has been successfully updated.'
};