var translationsFR = {
    BRAND: 'Outils Symbaroum',
    SEARCH: 'Recherche',
    LIENS: 'Liens externes',
    HELP: 'Aide',
    REGLES: 'Règles',
    TRUE: 'Oui',
    FALSE: 'Non',
    TYPE_TOUS: 'Type (tous)',
    TYPE_TALENT: 'talent',
    TYPE_POUVOIR_MYSTIQUE: 'pouvoir mystique',
    TYPE_QUALITE: 'qualite',
    TYPE_TRAIT_MONSTRUEUX: 'trait monstrueux',
    TYPE_TRAIT: 'trait',
    TYPE_ATOUT: 'atout',
    TYPE_FARDEAU: 'fardeau',
    TYPE_ELIXIR: 'elixir',
    TYPE_RITUEL: 'rituel',
    TYPE_ARME: 'arme',
    TYPE_ARMURE: 'armure',
    BOOK: 'Livre',
    BOOK_TOUS: 'Livre (tous)',
    BOOK_LDB: 'livre de base',
    BOOK_GDJ: 'guide du joueur',
    BOOK_CDX: 'codex des monstres',
    BOOK_ADV: 'aventures',
    TRAD_TOUS: 'Arch./Trad. (toutes)',
    TRAD_AUCUNE: 'aucune',
    TRAD_GUERRIER: 'guerrier',
    TRAD_MYSTIQUE: 'mystique',
    TRAD_ROUBLARD: 'roublard',
    TRAD_CHASSEUR: 'chasseur',
    TRAD_MAGIE: 'magie',
    TRAD_THEURGIE: 'théurgie',
    TRAD_SORCELLERIE: 'sorcellerie',
    TRAD_CONJURATION: 'conjuration',
    TRAD_TROLLS: 'chant des trolls',
    TRAD_SYMBOLISME: 'symbolisme',
    TRAD_BATON: 'mages au bâton',
    TRAD_BLESSING: 'benediction',
    NAME: 'Nom',
    AGI: 'AGI',
    FOR: 'FOR',
    PRE: 'PRE',
    VOL: 'VOL',
    VIG: 'VIG',
    DIS: 'DIS',
    AST: 'AST',
    PER: 'PER',
    INIT: 'INIT',
    INITIATIVE: 'Initiative',
    CATEG: 'Catégorie',
    DEF: 'DEF',
    END: 'END',
    SD: 'SD',
    SC: 'SC',
    CP: 'CP',
    DEG: 'DEG',
    ARM: 'ARM',
    DEFENSE: 'Défense',
    ARMURE: 'Armure',
    ENDURANCE: 'Endurance',
    RES_DOUL: 'Résistance à la douleur',
    SEUIL_CORR: 'Seuil de corruption',
    PERM_CORR: 'Corruption permanente',
    ARMES: 'Armes',
    TALENTS: 'Talents',
    TRAITS: 'Traits',
    NOTES: 'Notes',
    TACTICS: 'Tactiques',
    SHADOW: 'Ombre',
    EQUIPMENT: 'Equipement',
    EXPORT: 'Export',
    SAVE: 'Sauvegarder',
    COPIED: ' copié',
    IMPORT_JSON: 'Import',
    B64: 'Générer un lien',
    DISP_DESC: 'Afficher descriptions',
    RECH_DESC: 'Recherche aussi dans description',
    PINS: 'Epinglés seulement',
    PINS_TITLE: "N'afficher que les talents épinglés, que ce soit au niveau du nom du talent (dans ce cas, tous les niveaux sont visibles) ou d'un ou des niveaux (dans ce cas, seuls les niveaux épinglés sont visibles).",
    SEARCH_TITLE: "Champ de recherche. Les mots clés doivent être séparés par une virgule. Terminer par une virgule pour tout afficher à nouveau. Exemple : 'berserk,vif,'.",
    EXPORT_TITLE: "Format JSON",
    DOWNLOAD: "Télécharger",
    FOUNDRY_EXPORT_TITLE: "Macro FoundryVTT",
    FOUNDRY_EXPORT: "Copier le JSON dans le presse-papier",
    B64_TITLE: "Générer un lien encodé.",
    PINS_TITLE_ALL: 'Epingler entièrement.',
    PINS_TITLE_NOV: 'Epingler le niveau novice.',
    PINS_TITLE_ADP: 'Epingler le niveau adepte.',
    PINS_TITLE_MAI: 'Epingler le niveau maitre.',
    B84_PAN_TITLE: "Favoris",
    B84_PAN_LINK: "Lien",
    PAN_CLOSE: "Fermer",
    ATTR_TOUS: "Test (tous)",
    ATTR_AST: "Astuce",
    ATTR_DIS: "Discrétion",
    ATTR_AGI: "Agilité",
    ATTR_PER: "Persuasion",
    ATTR_FOR: "Force",
    ATTR_VIG: "Vigilance",
    ATTR_VOL: "Volonté",
    ATTR_PRE: "Précision",
    ATTR_PERVOL: "Persuasion <- Volonté",
    ATTR_ASTFOR: "Astuce <- Force",
    ATTR_ASTAST: "Astuce <- Astuce",
    ATTR_DISVIG: "Discrétion <- Vigilance",
    ATTR_FORFOR: "Force <- Force",
    ATTR_PREFOR: "Précision <- Force",
    ATTR_PREAGI: "Précision <- Agilité",
    ATTR_ASTAGI: "Astuce <- Agilité",
    ATTR_AGIFOR: "Agilité <- Force",
    ATTR_PREVOL: "Précision <- Volonté",
    ATTR_FORAGI: "Force <- Agilité",
    DAV_CLAIR: "Clair",
    DAV_SAUVAGE: "Sauvage",
    DAV_SOMBRE: "Sombre",
    DAV_SURVIE: "Survie",
    NOVICE: "Novice",
    ADEPTE: "Adepte",
    MAITRE: "Maître",
    DAV_JOURNEE: "Passer une journée en Davokar",
    DAV_TRESORS: "Trésors trouvés",
    DAV_PROV: "Provisions",
    DAV_NBPJ: "Nb. PNJ",
    DAV_SURPLACE: "Rester sur place",
    DAV_INFO: "Information orale",
    DAV_INFO_ECRITE: "Source écrite",
    DAV_INFO_ECRITE_SUP5: "Réussite jet > 5",
    DAV_ORIENTATION: "Orientation",
    DAV_RUINE: "Ruine",
    DAV_TRESOR: "Trésor",
    DAV_RENCONTRE: "Rencontre",
    DAV_ENNEMI: "Ennemis",
    DAV_TERRAIN: "Terrain",
    DAV_NONE: "Rien.",
    DAV_DEBRIS: "Débris",
    DAV_CURIOSITE: "Curiosité",
    DAV_MYSTIQUE: "Trésor mystique",
    DAV_ARTEFACT: "Artefact",
    DAV_ALERTE_VIG: "Saisir la Vigilance du chercheur de trésor !",
    DAV_REPERE: " Vous n'avez pas été repéré.",
    DAV_TRES_RESTANT: "Restant",
    AJOUT_ACTEUR: "Ajouter un acteur",
    SORT_INIT: "Trier",
    HIDE_ABILITIES: "Cacher la description des talents",
    NEW_TAB: "Ouvrir dans un nouvel onglet",
    MANAGE_INTEGRATED: "Gérer les talents intégrés",
    INTEGRATED: "Intégré",
    SPENT_POINTS: "Pts. Dépensés : ",
    STD_ARRAY: "Répartition classique : ",
    OPEN: "Ouvrir",
    MY_PC_NPC: "Mes PJ/PNJ/Monstres",
    SESSION_MSG: "Attention, ce site Web ne gère pas les sessions, ne rafraichissez pas la page ou il sera nécessaire de se réauthentifier.",
    LOG_IN: "Connexion",
    SIGN_UP: "Inscription",
    PWD: "Mot de passe",
    EMAIL: "Adresse email",
    LOGOUT: "Déconnexion",
    
    // SymbatooTools API errors
    ERR_LOG_1: "Adresse email inconnue.",
    ERR_LOG_2: "Mot de passe incorrect.",
    ERR_LOG_3: "Compte en cours de validation.",
    ERR_REG_1: "Adresse email ou mot de passe manquant.",
    ERR_REG_2: "Format de l'adresse email incorrect.",
    ERR_REG_3: "Adresse email déjà enregistrée.",
    ERR_REG_4: "Email de validation non envoyé, merci de contacter l'administrateur.",
    ERR_RES_1: "Email de reset de mot de passe non envoyé, merci de contacter l'administrateur.",
    ERR_API_1: "La requête a été envoyée mais n'est pas valide, merci de contacter l'administrateur.",

    // SymbaTools reset pwd messages
    MSG_RES_EMAIL_SENT: 'Un email vous a été envoyé avec le token à saisir.',
    MSG_RES_TOKEN_OK: 'Le token a été validé, merci de saisir votre nouveau mot de passe.',
    MSG_RES_PWD_CHANGED: 'Votre mot de passe a été mis à jour avec succès.'
};